blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/netzulo/autonomousworld-vscode/discussions
    about: Use Discussions for general questions or brainstorming
